import ast
import asyncio
import json
import os
import tempfile
import unittest
from unittest import mock

import server


class InstructionTests(unittest.TestCase):
    def test_uat_debug_is_the_default_integration_variant(self):
        self.assertIn("always build, install, and test the UAT Debug", server.MCP_INSTRUCTIONS)
        self.assertIn("unless the user explicitly requests that different", server.MCP_INSTRUCTIONS)
        self.assertIn("environment in the current chat", server.MCP_INSTRUCTIONS)
        self.assertIn("never silently substitute another variant", server.MCP_INSTRUCTIONS)


class _FakeProcess:
    def __init__(self, stdout: bytes, stderr: bytes = b"", returncode: int = 0):
        self._stdout = stdout
        self._stderr = stderr
        self.returncode = returncode

    async def communicate(self):
        return self._stdout, self._stderr


class _RunningProcess:
    def __init__(self):
        self.pid = 12345
        self.returncode = None

    async def wait(self):
        self.returncode = -15
        return self.returncode


class DeviceSelectionTests(unittest.IsolatedAsyncioTestCase):
    async def test_selects_the_only_online_network_device(self):
        output = b"List of devices attached\n192.168.1.8:5555\tdevice\n"
        with mock.patch(
            "server.asyncio.create_subprocess_exec",
            return_value=_FakeProcess(output),
        ):
            self.assertEqual(
                await server._resolve_adb_device(),
                "192.168.1.8:5555",
            )

    async def test_refuses_to_guess_when_multiple_devices_are_online(self):
        output = b"List of devices attached\nemulator-5554\tdevice\n192.168.1.8:5555\tdevice\n"
        with mock.patch(
            "server.asyncio.create_subprocess_exec",
            return_value=_FakeProcess(output),
        ):
            with self.assertRaisesRegex(RuntimeError, "Multiple ADB devices"):
                await server._resolve_adb_device()

    async def test_owned_process_group_is_terminated(self):
        process = _RunningProcess()
        with mock.patch("server.os.killpg") as killpg:
            self.assertTrue(await server._terminate_process_group(process))
        killpg.assert_called_once_with(process.pid, server.signal.SIGTERM)


class GeneratorCompatibilityTests(unittest.TestCase):
    def test_generated_appium_script_is_dynamic_and_import_compatible(self):
        script = server._build_appium_test_script(
            "com.example.app", ".MainActivity", [], [], [], "test_flow"
        )
        ast.parse(script)
        self.assertIn("from appium.options.android import UiAutomator2Options", script)
        self.assertIn("from appium.options import UiAutomator2Options", script)
        self.assertIn("ANDROID_DEVICE_UDID", script)
        self.assertIn("options.udid = device_udid", script)
        self.assertNotIn('device_name = "emulator-5554"', script)

    def test_okhttp_3_uses_java_style_methods(self):
        with tempfile.TemporaryDirectory() as project:
            with open(os.path.join(project, "build.gradle"), "w") as handle:
                handle.write("ext.okhttpVersion = '3.9.0'\n")
            major, style, method, path = server._okhttp_request_accessors(project)
        self.assertEqual((major, style), (3, "java-methods"))
        self.assertEqual(method, "request.method()")
        self.assertEqual(path, "request.url().encodedPath()")

    def test_okhttp_4_uses_kotlin_properties(self):
        with tempfile.TemporaryDirectory() as project:
            with open(os.path.join(project, "build.gradle.kts"), "w") as handle:
                handle.write('val okhttpVersion = "4.12.0"\n')
            major, style, method, path = server._okhttp_request_accessors(project)
        self.assertEqual((major, style), (4, "kotlin-properties"))
        self.assertEqual(method, "request.method")
        self.assertEqual(path, "request.url.encodedPath")


class MockCleanupTests(unittest.TestCase):
    def test_cleanup_removes_only_mcp_tagged_wiring(self):
        with tempfile.TemporaryDirectory() as project:
            app = os.path.join(project, "app")
            source = os.path.join(app, "src", "main", "Example.kt")
            user_mock = os.path.join(app, "src", "mockDebug", "UserMock.kt")
            generated = os.path.join(app, "src", "mockDebug", "MockApiInterceptor.kt")
            os.makedirs(os.path.dirname(source), exist_ok=True)
            os.makedirs(os.path.dirname(user_mock), exist_ok=True)
            with open(source, "w") as handle:
                handle.write(
                    "before\n"
                    f"{server.MOCK_NETWORK_BEGIN}\ntemporary\n"
                    f"{server.MOCK_NETWORK_END}\n"
                    "after\n"
                )
            with open(user_mock, "w") as handle:
                handle.write("// user-owned mock\n")
            with open(generated, "w") as handle:
                handle.write("// Generated by Kiro AndroidAutoDev MCP server\n")

            cleaned = server._remove_stale_temporary_mock_artifacts(project)

            self.assertIn(source, cleaned)
            self.assertIn(generated, cleaned)
            self.assertTrue(os.path.isfile(user_mock))
            self.assertFalse(os.path.exists(generated))
            with open(source) as handle:
                self.assertEqual(handle.read(), "before\nafter\n")
            self.assertEqual(server._temporary_mock_artifacts(project), [])

    def test_discovers_mock_sessions_across_shared_project_root(self):
        with tempfile.TemporaryDirectory() as allowed_root, tempfile.TemporaryDirectory() as log_dir:
            allowed_root = os.path.realpath(allowed_root)
            projects = [
                os.path.join(allowed_root, "project-one"),
                os.path.join(allowed_root, "project-two"),
            ]
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", allowed_root), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                for project in projects:
                    os.makedirs(project)
                    manifest_path = server._mock_manifest_path(project)
                    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
                    with open(manifest_path, "w") as handle:
                        json.dump({"project_path": project}, handle)

                self.assertCountEqual(server._active_mock_projects(), projects)

    def test_ignores_mock_session_outside_shared_project_root(self):
        with tempfile.TemporaryDirectory() as allowed_root, tempfile.TemporaryDirectory() as log_dir:
            allowed_root = os.path.realpath(allowed_root)
            outside_project = os.path.join(log_dir, "outside-project")
            os.makedirs(outside_project)
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", allowed_root), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                manifest_path = server._mock_manifest_path(outside_project)
                os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
                with open(manifest_path, "w") as handle:
                    json.dump({"project_path": outside_project}, handle)

                self.assertEqual(server._active_mock_projects(), [])


class ReviewWorkspaceTests(unittest.IsolatedAsyncioTestCase):
    SAFE_DIFF = (
        "diff --git a/app/src/main/Example.kt b/app/src/main/Example.kt\n"
        "--- a/app/src/main/Example.kt\n"
        "+++ b/app/src/main/Example.kt\n"
        "@@ -1 +1 @@\n"
        "-old\n"
        "+new\n"
    )

    async def test_managed_workspace_is_outside_project_and_cleanup_isolated(self):
        with tempfile.TemporaryDirectory() as allowed_root, tempfile.TemporaryDirectory() as log_dir:
            project = os.path.join(allowed_root, "project")
            source = os.path.join(project, "app", "src", "main", "Example.kt")
            generated = os.path.join(project, "app", "build", "generated.txt")
            old_review_copy = os.path.join(project, "android-auto-review-copy", "stale.txt")
            original_git_marker = os.path.join(project, ".git", "original-only")
            os.makedirs(os.path.dirname(source), exist_ok=True)
            os.makedirs(os.path.dirname(generated), exist_ok=True)
            os.makedirs(os.path.dirname(old_review_copy), exist_ok=True)
            os.makedirs(os.path.dirname(original_git_marker), exist_ok=True)
            with open(source, "w") as handle:
                handle.write("old\n")
            with open(generated, "w") as handle:
                handle.write("generated\n")
            with open(old_review_copy, "w") as handle:
                handle.write("stale\n")
            with open(original_git_marker, "w") as handle:
                handle.write("must not be copied\n")

            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", allowed_root), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                prepared = await server.prepare_code_review_workspace(project)
                workspace = prepared["workspace_path"]

                self.assertEqual(prepared["status"], "SUCCESS")
                self.assertFalse(workspace.startswith(project + os.sep))
                self.assertEqual(server._validate_gradle_project_path(workspace), workspace)
                self.assertTrue(os.path.isfile(os.path.join(workspace, "app", "src", "main", "Example.kt")))
                self.assertFalse(os.path.exists(os.path.join(workspace, "app", "build")))
                self.assertFalse(os.path.exists(os.path.join(workspace, "android-auto-review-copy")))
                self.assertTrue(os.path.isdir(os.path.join(workspace, ".git")))
                self.assertFalse(os.path.exists(os.path.join(workspace, ".git", "original-only")))

                cleaned = await server.cleanup_code_review_workspace(project, workspace)

                self.assertEqual(cleaned["status"], "SUCCESS")
                self.assertFalse(os.path.exists(workspace))
                with open(source) as handle:
                    self.assertEqual(handle.read(), "old\n")

    async def test_request_review_removes_managed_workspace(self):
        with tempfile.TemporaryDirectory() as allowed_root, tempfile.TemporaryDirectory() as log_dir:
            project = os.path.join(allowed_root, "project")
            os.makedirs(project)
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", allowed_root), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                prepared = await server.prepare_code_review_workspace(project)
                workspace = prepared["workspace_path"]

                review = await server.request_code_review(
                    project,
                    "Update Example",
                    self.SAFE_DIFF,
                    review_workspace_path=workspace,
                )

                self.assertEqual(review["status"], "AWAITING_USER_REVIEW")
                self.assertTrue(review["review_workspace_removed"])
                self.assertFalse(os.path.exists(workspace))

    def test_unregistered_temp_copy_is_rejected(self):
        with tempfile.TemporaryDirectory() as allowed_root, tempfile.TemporaryDirectory() as log_dir, tempfile.TemporaryDirectory() as arbitrary_copy:
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", allowed_root), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                with self.assertRaisesRegex(ValueError, "outside allowed root"):
                    server._validate_gradle_project_path(arbitrary_copy)

    async def test_expired_workspace_is_removed(self):
        with tempfile.TemporaryDirectory() as allowed_root, tempfile.TemporaryDirectory() as log_dir:
            project = os.path.join(allowed_root, "project")
            os.makedirs(project)
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", allowed_root), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                prepared = await server.prepare_code_review_workspace(project)
                workspace = prepared["workspace_path"]
                manifest_path = server._review_workspace_manifest_path(workspace)
                with open(manifest_path) as handle:
                    manifest = json.load(handle)
                manifest["expires_at_epoch"] = 0
                with open(manifest_path, "w") as handle:
                    json.dump(manifest, handle)

                removed = server._cleanup_review_workspaces()

                self.assertEqual(removed, [workspace])
                self.assertFalse(os.path.exists(workspace))


class CodeReviewGateTests(unittest.IsolatedAsyncioTestCase):
    SAFE_DIFF = (
        "diff --git a/app/src/main/Example.kt b/app/src/main/Example.kt\n"
        "--- a/app/src/main/Example.kt\n"
        "+++ b/app/src/main/Example.kt\n"
        "@@ -1 +1 @@\n"
        "-old\n"
        "+new\n"
    )

    async def test_review_and_apply_exact_diff_once(self):
        with tempfile.TemporaryDirectory() as project, tempfile.TemporaryDirectory() as log_dir:
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", project), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                review = await server.request_code_review(
                    project,
                    "Update Example",
                    self.SAFE_DIFF,
                )
                self.assertEqual(review["status"], "AWAITING_USER_REVIEW")
                self.assertEqual(review["proposed_diff"], self.SAFE_DIFF)
                self.assertIn("```diff\n", review["review_markdown"])
                self.assertIn("\n-old\n+new\n```", review["review_markdown"])
                self.assertIn("Reply with **approve**", review["review_markdown"])
                self.assertNotIn("approval_token", review)

                premature = await server.record_code_review_decision(
                    project,
                    review["review_id"],
                    self.SAFE_DIFF,
                    "approve",
                    "",
                    user_confirmed=False,
                )
                self.assertEqual(premature["status"], "NEEDS_USER_DECISION")

                decision = await server.record_code_review_decision(
                    project,
                    review["review_id"],
                    self.SAFE_DIFF,
                    "approve",
                    "approve",
                    user_confirmed=True,
                )
                self.assertEqual(decision["status"], "APPROVED")

                with mock.patch(
                    "server._git_apply",
                    new=mock.AsyncMock(return_value=(0, "")),
                ) as git_apply:
                    applied = await server.apply_reviewed_patch(
                        project,
                        self.SAFE_DIFF,
                        decision["approval_token"],
                    )
                    reused = await server.apply_reviewed_patch(
                        project,
                        self.SAFE_DIFF,
                        decision["approval_token"],
                    )

                self.assertEqual(applied["status"], "SUCCESS")
                self.assertEqual(git_apply.await_count, 2)
                self.assertEqual(reused["status"], "FAILURE")
                self.assertIn("consumed", reused["error_output"])

    def test_review_markdown_uses_a_safe_fence(self):
        proposed_diff = self.SAFE_DIFF.replace("+new", "+`````new`````")

        review_markdown = server._format_review_diff_markdown(proposed_diff)

        self.assertIn("``````diff\n", review_markdown)
        self.assertIn(proposed_diff, review_markdown)
        self.assertIn("\n``````\n", review_markdown)

    async def test_change_request_closes_review_without_approval(self):
        with tempfile.TemporaryDirectory() as project, tempfile.TemporaryDirectory() as log_dir:
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", project), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                review = await server.request_code_review(
                    project, "Update Example", self.SAFE_DIFF
                )
                decision = await server.record_code_review_decision(
                    project,
                    review["review_id"],
                    self.SAFE_DIFF,
                    "request_changes",
                    "Please rename the method.",
                    user_confirmed=True,
                )

                self.assertEqual(decision["status"], "CHANGES_REQUESTED")
                self.assertEqual(decision["feedback"], "Please rename the method.")
                self.assertNotIn("approval_token", decision)

    async def test_changed_diff_cannot_resolve_pending_review(self):
        with tempfile.TemporaryDirectory() as project, tempfile.TemporaryDirectory() as log_dir:
            with mock.patch.object(server, "ALLOWED_PROJECT_ROOT", project), mock.patch.object(
                server, "LOG_DIR", log_dir
            ):
                review = await server.request_code_review(
                    project, "Update Example", self.SAFE_DIFF
                )
                decision = await server.record_code_review_decision(
                    project,
                    review["review_id"],
                    self.SAFE_DIFF.replace("+new", "+different"),
                    "approve",
                    "approve",
                    user_confirmed=True,
                )

                self.assertEqual(decision["status"], "FAILURE")
                self.assertIn("changed while awaiting review", decision["error_output"])

    async def test_changed_diff_cannot_use_approval_token(self):
        with tempfile.TemporaryDirectory() as project, tempfile.TemporaryDirectory() as log_dir:
            with mock.patch.object(server, "LOG_DIR", log_dir):
                token, _ = server._store_code_review(
                    project, "Update Example", self.SAFE_DIFF
                )
                with self.assertRaisesRegex(ValueError, "changed after approval"):
                    server._authorize_reviewed_diff(
                        project,
                        self.SAFE_DIFF.replace("+new", "+different"),
                        token,
                    )

    def test_rejects_path_traversal_and_binary_patches(self):
        traversal = self.SAFE_DIFF.replace(
            "a/app/src/main/Example.kt b/app/src/main/Example.kt",
            "a/../secret b/../secret",
        )
        with self.assertRaisesRegex(ValueError, "Unsafe path"):
            server._validate_review_diff(traversal)
        with self.assertRaisesRegex(ValueError, "Binary patches"):
            server._validate_review_diff(self.SAFE_DIFF + "GIT binary patch\n")


if __name__ == "__main__":
    unittest.main()
