import ast
import asyncio
import os
import tempfile
import unittest
from unittest import mock

import server


class _FakeProcess:
    def __init__(self, stdout: bytes, stderr: bytes = b"", returncode: int = 0):
        self._stdout = stdout
        self._stderr = stderr
        self.returncode = returncode

    async def communicate(self):
        return self._stdout, self._stderr


class _RunningProcess:
    def __init__(self):
        self.pid = 12345
        self.returncode = None

    async def wait(self):
        self.returncode = -15
        return self.returncode


class DeviceSelectionTests(unittest.IsolatedAsyncioTestCase):
    async def test_selects_the_only_online_network_device(self):
        output = b"List of devices attached\n192.168.1.8:5555\tdevice\n"
        with mock.patch(
            "server.asyncio.create_subprocess_exec",
            return_value=_FakeProcess(output),
        ):
            self.assertEqual(
                await server._resolve_adb_device(),
                "192.168.1.8:5555",
            )

    async def test_refuses_to_guess_when_multiple_devices_are_online(self):
        output = b"List of devices attached\nemulator-5554\tdevice\n192.168.1.8:5555\tdevice\n"
        with mock.patch(
            "server.asyncio.create_subprocess_exec",
            return_value=_FakeProcess(output),
        ):
            with self.assertRaisesRegex(RuntimeError, "Multiple ADB devices"):
                await server._resolve_adb_device()

    async def test_owned_process_group_is_terminated(self):
        process = _RunningProcess()
        with mock.patch("server.os.killpg") as killpg:
            self.assertTrue(await server._terminate_process_group(process))
        killpg.assert_called_once_with(process.pid, server.signal.SIGTERM)


class GeneratorCompatibilityTests(unittest.TestCase):
    def test_generated_appium_script_is_dynamic_and_import_compatible(self):
        script = server._build_appium_test_script(
            "com.example.app", ".MainActivity", [], [], [], "test_flow"
        )
        ast.parse(script)
        self.assertIn("from appium.options.android import UiAutomator2Options", script)
        self.assertIn("from appium.options import UiAutomator2Options", script)
        self.assertIn("ANDROID_DEVICE_UDID", script)
        self.assertIn("options.udid = device_udid", script)
        self.assertNotIn('device_name = "emulator-5554"', script)

    def test_okhttp_3_uses_java_style_methods(self):
        with tempfile.TemporaryDirectory() as project:
            with open(os.path.join(project, "build.gradle"), "w") as handle:
                handle.write("ext.okhttpVersion = '3.9.0'\n")
            major, style, method, path = server._okhttp_request_accessors(project)
        self.assertEqual((major, style), (3, "java-methods"))
        self.assertEqual(method, "request.method()")
        self.assertEqual(path, "request.url().encodedPath()")

    def test_okhttp_4_uses_kotlin_properties(self):
        with tempfile.TemporaryDirectory() as project:
            with open(os.path.join(project, "build.gradle.kts"), "w") as handle:
                handle.write('val okhttpVersion = "4.12.0"\n')
            major, style, method, path = server._okhttp_request_accessors(project)
        self.assertEqual((major, style), (4, "kotlin-properties"))
        self.assertEqual(method, "request.method")
        self.assertEqual(path, "request.url.encodedPath")


class MockCleanupTests(unittest.TestCase):
    def test_cleanup_removes_only_mcp_tagged_wiring(self):
        with tempfile.TemporaryDirectory() as project:
            app = os.path.join(project, "app")
            source = os.path.join(app, "src", "main", "Example.kt")
            user_mock = os.path.join(app, "src", "mockDebug", "UserMock.kt")
            generated = os.path.join(app, "src", "mockDebug", "MockApiInterceptor.kt")
            os.makedirs(os.path.dirname(source), exist_ok=True)
            os.makedirs(os.path.dirname(user_mock), exist_ok=True)
            with open(source, "w") as handle:
                handle.write(
                    "before\n"
                    f"{server.MOCK_NETWORK_BEGIN}\ntemporary\n"
                    f"{server.MOCK_NETWORK_END}\n"
                    "after\n"
                )
            with open(user_mock, "w") as handle:
                handle.write("// user-owned mock\n")
            with open(generated, "w") as handle:
                handle.write("// Generated by Kiro AndroidAutoDev MCP server\n")

            cleaned = server._remove_stale_temporary_mock_artifacts(project)

            self.assertIn(source, cleaned)
            self.assertIn(generated, cleaned)
            self.assertTrue(os.path.isfile(user_mock))
            self.assertFalse(os.path.exists(generated))
            with open(source) as handle:
                self.assertEqual(handle.read(), "before\nafter\n")
            self.assertEqual(server._temporary_mock_artifacts(project), [])


if __name__ == "__main__":
    unittest.main()
